### PR TITLE
ifindex maps: convert ARRAY/DEVMAP to HASH variants (fixes #756)

### LINKED ISSUE #756: userspace-dp: CoS silently unenforced on VMs with ifindex > BPF map cap
## What happened

`iperf3 -c 172.16.80.200 -P 1 -t 60 -p 5201` through the loss **bpfrx-fw** cluster (reth0.80, CoS `iperf-a` scheduler `transmit-rate 1.0g exact`) exceeds the 1 Gbps cap at line rate. Meanwhile the same test through the loss **xpf-userspace-fw** cluster sits at 954 Mbps (under cap).

## Root cause

The bpfrx-fw VM has accumulated ifindex values into the thousands (`fab0=3651`, `fab1=3652`, `vrf-sfmix=3643`, …). Several BPF maps keyed on ifindex are sized too small:

| Map | Type | max_entries | Declared in |
|---|---|---|---|
| `tx_ports` | `BPF_MAP_TYPE_DEVMAP` | `MAX_INTERFACES` (2048) | `bpf/headers/xpf_maps.h:339-344` |
| `redirect_capable` | `BPF_MAP_TYPE_ARRAY` | `MAX_INTERFACES` (2048) | `bpf/headers/xpf_maps.h:349-354` |
| `interface_counters` | `BPF_MAP_TYPE_PERCPU_ARRAY` | `MAX_INTERFACES` (2048) | `bpf/headers/xpf_maps.h:307-312` |
| `mirror_config` | `BPF_MAP_TYPE_ARRAY` | `MAX_INTERFACES` (2048) | `bpf/headers/xpf_maps.h:780-785` |
| `userspace_ingress_ifaces` | `Array<u8>` (aya) | 1024 | `userspace-xdp/src/lib.rs:269-270` |

Updates with `key >= max_entries` return `E2BIG` (`"update: key too big for map: argument list too long"`). The resulting chain:

1. `compileDataplane` returns `compile zones: add tx port fab0: update: key too big for map`.
2. Snapshot apply aborts before `ensureProcessLocked`, so the userspace-dp helper is never spawned.
3. Control socket is never opened. The reconcile loop retries `UpdateRGActive` every 500 ms, each time logging `userspace: RG state updated (helper stays in control)` at INFO and `reconcile: failed to update rg_active ... err="userspace dataplane control socket not configured"` at WARN.
4. Traffic flows through the eBPF kernel path, which has no CoS admission policer. iperf3 sees no cap.

## Evidence

```
Apr 18 15:38:14 xpf-fw1 xpfd[3637081]: ... msg="failed to compile dataplane" err="compile zones: add tx port fab0: update: key too big for map: argument list too long"
Apr 18 15:34:26 bpfrx-fw0 bpfrxd[727]: ... msg="userspace dataplane status sync failed" err="update userspace_ingress_ifaces 2044: update: key too big for map: argument list too long"
```

```
$ ip -o link | awk -F: '{print $1}' | sort -n | tail
3643  vrf-sfmix
3644  vrf-mgmt
3650  gr-0-0-0
3651  fab0
3652  fab1
```

On xpf-userspace-fw0 (working cluster) the max ifindex is 630 — under every cap.

## Fix

Convert ifindex-keyed maps to their HASH variants so sparse keys are supported regardless of ifindex value. Concretely:

- `tx_ports`: `BPF_MAP_TYPE_DEVMAP` → `BPF_MAP_TYPE_DEVMAP_HASH`
- `redirect_capable`, `mirror_config`: `BPF_MAP_TYPE_ARRAY` → `BPF_MAP_TYPE_HASH` + `BPF_F_NO_PREALLOC`
- `interface_counters`: `BPF_MAP_TYPE_PERCPU_ARRAY` → `BPF_MAP_TYPE_PERCPU_HASH` + `BPF_F_NO_PREALLOC`
- `userspace_ingress_ifaces` (aya): `Array<u8>` → `HashMap<u32, u8>`

`bpf_redirect_map` and `bpf_map_lookup_elem` both work identically with HASH flavours.

## Related

Separate issues cover downstream symptoms that would still bite even after this is fixed:
- reconcile log flood when helper is down
- silent-spin on `failed to compile dataplane` (no retry, no alarm)

### PR DESCRIPTION
**Pull request by psaab**
## Summary

CoS admission was silently unenforced on long-lived VMs where kernel ifindex exceeded the BPF map caps. Running \`iperf3 -c 172.16.80.200 -P 1 -t 60 -p 5201\` against a \`transmit-rate 1.0g exact\` scheduler returned line rate instead of the 1 Gbps cap because the userspace-dp helper never spawned — snapshot compile failed with \`add tx port fab0: update: key too big for map: argument list too long\` for ifindex 3651.

Convert all ifindex-keyed maps to HASH flavours so sparse keys work regardless of ifindex magnitude.

## Changes

- \`bpf/headers/xpf_maps.h\`:
  - \`tx_ports\`: \`BPF_MAP_TYPE_DEVMAP\` → \`BPF_MAP_TYPE_DEVMAP_HASH\`
  - \`redirect_capable\`: \`BPF_MAP_TYPE_ARRAY\` → \`BPF_MAP_TYPE_HASH\` + \`BPF_F_NO_PREALLOC\`
  - \`mirror_config\`: same treatment
  - \`interface_counters\`: \`BPF_MAP_TYPE_PERCPU_ARRAY\` → \`BPF_MAP_TYPE_PERCPU_HASH\` + \`BPF_F_NO_PREALLOC\`
- \`bpf/headers/xpf_helpers.h\` (\`inc_iface_rx\` / \`inc_iface_tx\`): hot path stays lookup-only. Counters are seeded from the control plane, so softirq never allocates.
- \`userspace-xdp/src/lib.rs\`: \`USERSPACE_INGRESS_IFACES\`: \`Array<u8>\` → \`HashMap<u32, u8>\` + callsite updated to \`get(&ingress_ifindex)\`.
- \`pkg/dataplane/loader.go\`: \`seedInterfaceCounter(ifindex)\` idempotently pre-populates \`interface_counters\` via \`UpdateNoExist\`. Called from \`AddTxPort\` (redirect targets) and \`AttachXDP\` (ingress-attached interfaces), covering every interface the BPF hot path can touch.
- \`pkg/dataplane/userspace/maps_sync.go\`: \`syncIngressIfaceMapLocked\` uses \`Delete\` for stale keys. A non-\`ErrKeyNotExist\` failure is fatal — a stale entry the dataplane still treats as ingress would silently redirect.
- \`pkg/dataplane/maps.go\`:
  - \`ClearInterfaceCounters\` / \`ClearMirrorConfigs\` iterate existing keys, check \`iter.Err()\`, and propagate \`Update\`/\`Delete\` errors.
  - \`ReadInterfaceCounters\` returns zero for \`ErrKeyNotExist\` rather than surfacing an error.

## Hot-path shape — honest accounting

The hot path is no longer an O(1) array index — it is a hash probe per packet for the ifindex-keyed maps (\`userspace_ingress_ifaces\`, \`tx_ports\`, \`redirect_capable\`, \`mirror_config\`, \`interface_counters\`). A kernel HASH probe is ~5-10 ns, so on a loaded worker at ~850K pps per queue the per-packet cost is on the order of hundreds of ns/sec at rate — not free, but below the noise floor of the admission layer we care about.

- \`bpf_redirect_map()\` behaviour is identical between \`DEVMAP\` and \`DEVMAP_HASH\`.
- Counter-side hot path is **unchanged from master** (lookup + conditional increment). The seeding moved entirely to the control plane, so the softirq path never calls \`bpf_map_update_elem\` (this is a correctness win over the first iteration of this PR, which attempted lazy seeding from BPF).
- Memory: HASH + \`NO_PREALLOC\` allocates only for live interfaces, not \`max_entries\`. Net reduction.

If this overhead ever shows up in a real profile, #761 tracks a dense-slot follow-up (compact \`slot_id\` indirection; hot-path maps keyed by slot, not ifindex).

## Test plan

- [x] \`make generate\` regenerates bpf2go bindings cleanly
- [x] \`make build\` OK
- [x] \`make test\` — all Go tests pass
- [x] Deploy to loss:bpfrx-fw cluster (ifindex 3651 for fab0)
- [x] Verify \`config compiled to dataplane\` replaces \`add tx port fab0: key too big\`
- [x] Verify \`userspace dataplane helper started\` and event stream connects
- [x] Verify XSK bindings populate for fabric, LAN, and WAN × 4 queues each
- [x] Confirm the reconcile log-flood stops

## Live data

Pre-change bpfrx-fw1 boot (ifindex 3651):
\`\`\`
level=WARN msg=\"failed to compile dataplane\" err=\"compile zones: add tx port fab0: update: key too big for map: argument list too long\"
level=WARN msg=\"reconcile: failed to update rg_active\" err=\"userspace dataplane control socket not configured\"  # 9 log lines/sec forever
\`\`\`

Post-change bpfrx-fw0 boot (same ifindex topology):
\`\`\`
level=INFO msg=\"config compiled to dataplane\" zones=5 addresses=2 applications=0 policy_sets=2
level=INFO msg=\"event stream: helper connected\"
level=INFO msg=\"userspace dataplane helper started\" pid=1646085 socket=/run/xpf/userspace-dp.sock
xpf-userspace-dp: reconcile planned_workers=4 planned_bindings=12 live_slots=12
bound if4q0..q3 (fabric), if5q0..q3 (LAN), if6q0..q3 (WAN)
\`\`\`

Helper is now running; CoS queue state goes from \"Runtime: unavailable\" to \`Runtime workers: 2, nonempty=1\`.

## Deferred

- **#761** — dense-slot design so the hot path stops probing ifindex hashes. Should be driven by perf data (\`perf stat -e dTLB-load-misses,L1-dcache-load-misses\` during iperf3) before we decide it's worth doing.
- **#760** — even with helper in path, single-flow iperf3 drifts to ~1.5 Gbps against a 1 Gbps \`exact\` cap (observed on loss:xpf-userspace-fw0 which was always unaffected by the ifindex bug). Distinct CoS admission-rate issue, not this PR.

## Refs

Fixes #756
Related: #757 (reconcile log flood), #758 (silent compile failure), #760 (CoS cap overshoot), #761 (dense-slot follow-up)

### CODE REVIEW

File: bpf/headers/xpf_helpers.h [hunk 1]
```diff
@@ -1029,17 +1029,30 @@ inc_screen_counter(__u32 screen_flag)
...
+/* interface_counters is a PERCPU_HASH (#756). On the first packet for a
+ * given ifindex, lookup returns NULL; seed the entry with zeros then
+ * increment. The NOEXIST flag makes the seeding race-safe across cores. */
 static __always_inline void
 inc_iface_rx(__u32 ifindex, __u32 pkt_len)
 {
 	struct iface_counter_value *ic = bpf_map_lookup_elem(&interface_counters, &ifindex);
+	if (!ic) {
+		struct iface_counter_value zero = {};
+		bpf_map_update_elem(&interface_counters, &ifindex, &zero, BPF_NOEXIST);
```
Comment (psaab) [inline bpf/headers/xpf_helpers.h]: Medium: `interface_counters` moved from `PERCPU_ARRAY` to `PERCPU_HASH`, and this miss path now does lookup -> update(NOEXIST) -> re-lookup directly from the packet path. That is fine for correctness, but it is not a low-latency shape: the first packet on a new ifindex now pays allocator/update work in softirq/XDP/TC context. If we keep the hash map, I would rather pre-seed counter entries from control plane when interfaces are registered and make the dataplane miss path a no-op (or a debug-only fallback) so the hot path never allocates.

File: userspace-xdp/src/lib.rs [hunk 2]
```diff
@@ -355,8 +358,7 @@ fn try_xdp_userspace(ctx: &XdpContext) -> Result<u32, i64> {
     };
 
     let ingress_ifindex = unsafe { (*ctx.ctx).ingress_ifindex };
-    if USERSPACE_INGRESS_IFACES
-        .get(ingress_ifindex)
+    if unsafe { USERSPACE_INGRESS_IFACES.get(&ingress_ifindex) }
```
Comment (psaab) [inline userspace-xdp/src/lib.rs:361]: Medium: the PR summary says the hot-path behaviour is "steady state identical", but this map is now a hash probe on every userspace-XDP packet before the program decides cpumap-or-pass. The same is true for `redirect_capable` and `mirror_config` in the XDP forward path, and for `interface_counters` once seeded. That may still be the right correctness tradeoff for sparse ifindex, but it is not identical. I would either 1) tone down the claim and include perf numbers for the new steady-state shape, or 2) split out a follow-up dense-slot design (sparse ifindex -> compact slot, hot arrays behind it) if this path matters for latency.

**Comment by psaab** [comment]
HFT/netdev performance review:

1. `interface_counters` is now a `PERCPU_HASH`, and the new miss path seeds entries from XDP/TC packet context. That fixes correctness, but it is a worse latency shape than pre-seeding from control plane.
2. The PR summary currently overclaims the perf result. `redirect_capable`, `mirror_config`, `interface_counters`, and `userspace_ingress_ifaces` are no longer array lookups; they are hash lookups in packet paths. That may be acceptable to fix sparse-ifindex correctness, but it is not steady-state identical and should be described or measured as such.

I left two inline comments with concrete alternatives.
